services:
  - type: web
    name: server-health-check
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --workers 2 --timeout 600 --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
